language: ruby
#test
before_install:
  - gem install bundler
rvm:
      - 3.0.0
cache:
  - bundler
services:
  - postgresql
before_script:
  - psql -c 'create database authgit_test;' -U postgres
test:
  adapter: postgresql
  database: authgit_test
script:
  - bundle exec rspec spec --format documentation
deploy:
  provider: heroku
  api_key: 8e661bb5-d4dc-4e56-91fc-d109ef25e5c5
  app: shrouded-caverns-92109
  on:
    all_branches: true
    repo: KravchenkoAndrey24/RailsForArticles
